Lock version

diff --git a/bin/s3-to-pg b/bin/s3-to-pg
--- a/bin/s3-to-pg
+++ b/bin/s3-to-pg
@@ -15,4 +15,13 @@ if [ -z "$database_url" ]; then
   exit 1
 fi
 
-aws s3 cp "$s3_dump" - | pg_restore --clean --if-exists -d "$database_url"
+if [ -z "$FORCE_DELETE" ]; then
+  read -p "This will drop the database. Continue? (y/N) " -n 1 -r
+
+  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+    echo "Aborting..."
+    exit 1
+  fi
+fi
+
+#aws s3 cp "$s3_dump" - | pg_restore --clean --if-exists -d "$database_url"
